### ISSUE TITLE
Arreglar y optimizar getLastUsers 

### ISSUE THREAD

**Issue by fniwes** [martofeld/meliBook#5]
El método indexController:getLastUsers tiene varios issues..
1. No es un action.
2. En lo personal me parece que pertenece a la clase User, asi que lo crearía como un método estático de User.
3.No debe iterar por toda la base de datos. Debe retornar los últimos 3 directamente. Para eso se puede usar tanto findAll o list, ambos métodos aceptan por parámetro un ordenamiento Y un limite de registros a retornar.

**Comment by fniwes** [comment]
Y en que commit se arregla este problema? no referenciaste al issue en el commit :(

**Comment by martofeld** [comment]
No hice el commit todavia, despues subo todo de una
